[general]
app_name = "libra"
log_level = 1
log_path = "./log/"

[server]
http_port = 9002
grpc_port = 8001
grpc_protocol = "tcp"
# 开启链路追踪
grpc_trace_enable = true


[worker.weather]
name = "weather"
corn = "0/50 * * * * ?"

[system.trace]
service_name = "simple-svr"
host_port = "127.0.0.1:6831"

[grpc.client.search]
host_port = "127.0.0.1:8002"